#!/usr/bin/env sh

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Convenient way to invoke a gradle command with all Scala versions supported
# by default
# This script was originally designed to support multiple Scala versions (2.12 and 2.13),
# but as Scala 2.12 is no longer supported, this script is no longer necessary.
# We are keeping it for backwards compatibility. It will be removed in a future release.
echo "Warning: This script is deprecated and will be removed in a future release."
./gradlew "$@" -PscalaVersion=2.13

