clusters=primary,standby

primary.bootstrap.servers=primary:9092
standby.bootstrap.servers=standby:9094

primary->standby.enabled=true
primary->standby.topics=commit-log

primary->standby.emit.checkpoints.enabled=true
primary->standby.emit.checkpoints.interval.seconds=5

primary->standby.emit.heartbeats.enabled=true
primary->standby.emit.heartbeats.interval.seconds=5

primary->standby.sync.topic.acls.enabled=false
# Force the internal replication consumer to crash on out-of-range/truncation gaps
primary->standby.consumer.auto.offset.reset = none

replication.factor=1

offset-syncs.topic.replication.factor=1
checkpoints.topic.replication.factor=1
heartbeats.topic.replication.factor=1

offset.storage.replication.factor=1
status.storage.replication.factor=1
config.storage.replication.factor=1