clusters=primary,standby

primary.bootstrap.servers=primary-kafka:9092
standby.bootstrap.servers=standby-kafka:9092  

primary->standby.enabled=true
standby->primary.enabled=false

primary->standby.topics=.*

replication.factor=1

checkpoints.topic.replication.factor=1
heartbeats.topic.replication.factor=1
offset-syncs.topic.replication.factor=1

config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1

sync.group.offsets.enabled=true
refresh.topics.enabled=true
refresh.groups.enabled=true
emit.heartbeats.enabled=true

plugin.path=/opt/kafka/libs