#!/usr/bin/env bash
###############################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################


# Start kafka broker
# TODO: REMOVE THIS
echo "$(date +"%H:%M:%S.%3N") ===> Launching kafka ... "
/opt/kafka/bin/kafka-server-start.sh /etc/kafka/kafka.properties & # your first application
P1=$! # capture PID of the process

# Wait for process to exit
wait -n $P1
# Exit with status of process that exited first
exit $?
