@startuml
!theme plain
scale 10 as 50 pixels

title EventCountRange (1 event before, 1 event after)

' Define axes
concise "1. Event Time (s)" as ET
concise "2. Processing Time (s)" as PT
concise "3. State Store (Buffer)" as SS
concise "4. Range" as Out

' Initial State
@0
ET is Idle
PT is Idle
SS is "{ }"
Out is Idle

' --- Arrival 1: A ---
@25
PT is "A"
ET is "A"
SS is "{ A }"
Out is "{A}"
@35
PT is Idle
ET is Idle
Out is Idle

@45
ET is "B"

@55
ET is Idle

' --- Arrival 2: C ---
' System thinks C is the next event
@65
PT is "C"
ET is "C"
SS is "{A, C}"
Out is "{A, C}"
@75
PT is Idle
ET is Idle
Out is Idle

' --- Arrival 3: D ---
@85
PT is "D"
ET is "D"
SS is "{ A, C, D }"
Out is "{C, D}"
@95
PT is Idle
ET is Idle
Out is Idle

' --- Arrival 4: B (LATE DATA) ---
' B arrives out of order in processing time, but its event time is older
@122
PT is "B [LATE]"
SS is "{ A, B, C, D}"
Out is "{ A, B, C }"
note bottom of Out
    The after event
    is only in range on
    late arriving data
end note
@138
PT is Idle
Out is Idle

@145
@enduml