/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package unit.kafka.integration

import kafka.utils.TestUtils

import scala.jdk.CollectionConverters._
import org.junit.jupiter.api.BeforeEach
import com.yammer.metrics.core.Gauge
import org.apache.kafka.common.test.ClusterInstance
import org.apache.kafka.common.test.api.{ClusterConfigProperty, ClusterTest, Type}
import org.apache.kafka.server.config.{ReplicationConfigs, ServerConfigs, ServerLogConfigs}
import org.apache.kafka.server.metrics.KafkaYammerMetrics

//@ClusterTestDefaults(
//  types = Array(Type.KRAFT),
//  serverProperties = Array(
//    new ClusterConfigProperty(key = ServerConfigs.DELETE_TOPIC_ENABLE_CONFIG, value = "true"),
//    new ClusterConfigProperty(key = ServerLogConfigs.AUTO_CREATE_TOPICS_ENABLE_CONFIG, value = "false"),
//    // speed up the test for UnderReplicatedPartitions, which relies on the ISR expiry thread to execute concurrently with topic creation
//    // But the replica.lag.time.max.ms value still need to consider the slow Jenkins testing environment
//    new ClusterConfigProperty(key = ReplicationConfigs.REPLICA_LAG_TIME_MAX_MS_CONFIG, value = "4000"),
//    new ClusterConfigProperty(key = "log.segment.delete.delay.ms", value = "1000")
//  )
//)
class MetricsDuringTopicCreationDeletionTest(clusterInstance: ClusterInstance) {

  private val topicName = "topic"
  private val topicNum = 2
  private val topics = List.tabulate(topicNum) (n => topicName + n)

  private val replicationFactor = 3
  private val partitionNum = 3
  private val createDeleteIterations = 3

  private var running = true

  private var initialOfflinePartitionsCount = 0
  private var initialPreferredReplicaImbalanceCount = 0
  private var initialUnderReplicatedPartitionCount = 0

  /*
   * Captures initial values of key controller metrics.
   * These will be compared with final values to detect any changes.
   */
  @BeforeEach
  def setUp(): Unit = {
    try {
      initialOfflinePartitionsCount = getGauge("OfflinePartitionsCount").value
      initialPreferredReplicaImbalanceCount = getGauge("PreferredReplicaImbalanceCount").value
      initialUnderReplicatedPartitionCount = getGauge("UnderReplicatedPartitions").value
    } catch {
      case e: Exception => e.printStackTrace()
    }
  }

  /*
   * Checking all metrics we care in a single test is faster though it would be more elegant to have 3 @Test methods
   */
  @ClusterTest(
    types = Array(Type.KRAFT),
    serverProperties = Array(
      new ClusterConfigProperty(key = ServerConfigs.DELETE_TOPIC_ENABLE_CONFIG, value = "true"),
      new ClusterConfigProperty(key = ServerLogConfigs.AUTO_CREATE_TOPICS_ENABLE_CONFIG, value = "false"),
      new ClusterConfigProperty(key = ReplicationConfigs.REPLICA_LAG_TIME_MAX_MS_CONFIG, value = "4000"),
      new ClusterConfigProperty(key = "log.segment.delete.delay.ms", value = "1000")
    )
  )
  def testMetricsDuringTopicCreateDelete(): Unit = {

    // For OfflinePartitionsCount and PreferredReplicaImbalanceCount even with https://issues.apache.org/jira/browse/KAFKA-4605
    // the test has worked reliably because the metric that gets triggered is the one generated by the first started server (controller)
    val offlinePartitionsCountGauge = getGauge("OfflinePartitionsCount")
    @volatile var offlinePartitionsCount = offlinePartitionsCountGauge.value

    val preferredReplicaImbalanceCountGauge = getGauge("PreferredReplicaImbalanceCount")
    @volatile var preferredReplicaImbalanceCount = preferredReplicaImbalanceCountGauge.value

    // For UnderReplicatedPartitions, because of https://issues.apache.org/jira/browse/KAFKA-4605
    // we can't access the metrics value of each server. So instead we directly invoke the method
    // replicaManager.underReplicatedPartitionCount() that defines the metrics value.
    val underReplicatedPartitionCount = 0

    // Sanity check: ensure metrics haven't changed before test starts
    assert(offlinePartitionsCount == initialOfflinePartitionsCount)
    assert(preferredReplicaImbalanceCount == initialPreferredReplicaImbalanceCount)
    assert(underReplicatedPartitionCount == initialUnderReplicatedPartitionCount)

    // Thread that continuously checks for any change in metrics
    running = true
    val thread = new Thread(() => {
      while (running) {
        for (_ <- clusterInstance.brokers().asScala if running) {
          // Get UnderReplicatedPartitions through JMX
          val underReplicatedPartitionCount = KafkaYammerMetrics.defaultRegistry.allMetrics.asScala
            .find { case (k, _) => k.getName.endsWith("UnderReplicatedPartitions") }
            .map(_._2.asInstanceOf[Gauge[Int]].value)
            .getOrElse(0)
          if (underReplicatedPartitionCount != initialUnderReplicatedPartitionCount) {
            running = false
          }
        }

        offlinePartitionsCount = offlinePartitionsCountGauge.value
        if (offlinePartitionsCount != initialOfflinePartitionsCount) running = false

        preferredReplicaImbalanceCount = preferredReplicaImbalanceCountGauge.value
        if (preferredReplicaImbalanceCount != initialPreferredReplicaImbalanceCount) running = false
      }
    })
    thread.start()

    // Breakable loop that creates and deletes topics
    for (_ <- 1 to createDeleteIterations if running) {
      // Create topics
      for (topic <- topics if running) {
        try {
          clusterInstance.createTopic(topic, partitionNum, replicationFactor.toShort)
        } catch {
          case e: Exception => e.printStackTrace()
        }
      }

      // Delete topics
      for (topic <- topics if running) {
        try {
          clusterInstance.deleteTopic(topic)
          TestUtils.verifyTopicDeletion(topic, partitionNum, clusterInstance.brokers().asScala.values.toList)
        } catch {
          case e: Exception => e.printStackTrace()
        }
      }
    }

    // if the thread checking the gauge is still run, stop it
    running = false
    thread.join()

    assert(offlinePartitionsCount==initialOfflinePartitionsCount,
      s"Expect offlinePartitionsCount to be $initialOfflinePartitionsCount, but got: $offlinePartitionsCount")
    assert(preferredReplicaImbalanceCount==initialPreferredReplicaImbalanceCount,
      s"Expect PreferredReplicaImbalanceCount to be $initialPreferredReplicaImbalanceCount, but got: $preferredReplicaImbalanceCount")
    assert(underReplicatedPartitionCount==initialUnderReplicatedPartitionCount,
      s"Expect UnderReplicatedPartitionCount to be $initialUnderReplicatedPartitionCount, but got: $underReplicatedPartitionCount")
  }

  private def getGauge(metricName: String) = {
    KafkaYammerMetrics.defaultRegistry.allMetrics.asScala
      .find { case (k, _) => k.getName.endsWith(metricName) }
      .getOrElse(throw new AssertionError( "Unable to find metric " + metricName))
      ._2.asInstanceOf[Gauge[Int]]
  }
}
