clusters=primary,standby

primary.bootstrap.servers=primary:19092
standby.bootstrap.servers=standby:19092

primary->standby.enabled=true
standby->primary.enabled=false

primary->standby.topics=commit-log
primary->standby.emit.heartbeats.enabled=false
primary->standby.emit.checkpoints.enabled=false
primary->standby.sync.group.offsets.enabled=false

replication.factor=1
checkpoints.topic.replication.factor=1
heartbeats.topic.replication.factor=1
offset-syncs.topic.replication.factor=1

refresh.topics.enabled=true
refresh.topics.interval.seconds=1
sync.topic.configs.enabled=false
sync.topic.acls.enabled=false

offset.validation.enabled=true
consumer.poll.timeout.ms=500
