/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.kafka.server.policy;

import java.util.Objects;
import java.util.SortedSet;

/**
 * Immutable class containing the configuration profile keys.
 * <p>
 * A configuration profile defines the set of configuration keys to capture. The ClientConfigPolicy
 * uses the information in the client profile to select the most appropriate configuration profile.
 * <p>
 * The CRC is generated by calculating a CRC32C of the configuration keys and is used to detect
 * changes to the configuration profile between GetConfigProfileKeys and PushConfig requests.
 */
public final class ClientConfigProfileKeys {
    private final SortedSet<String> keys;
    private final long crc;

    /**
     * Creates a new ClientConfigProfileKeys.
     *
     * @param keys The set of configuration keys the client should provide (sorted for deterministic ordering)
     * @param crc  CRC32C checksum of the configuration keys for profile change detection
     */
    public ClientConfigProfileKeys(SortedSet<String> keys, long crc) {
        this.keys = keys;
        this.crc = crc;
    }

    public SortedSet<String> keys() {
        return keys;
    }

    public long crc() {
        return crc;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ClientConfigProfileKeys that = (ClientConfigProfileKeys) o;
        return crc == that.crc && Objects.equals(keys, that.keys);
    }

    @Override
    public int hashCode() {
        return Objects.hash(keys, crc);
    }

    @Override
    public String toString() {
        return "ClientConfigProfileKeys{" +
               "keys=" + keys +
               ", crc=" + crc +
               '}';
    }
}
