/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.kafka.server.policy;

import org.apache.kafka.common.Reconfigurable;
import org.apache.kafka.common.annotation.InterfaceStability;
import org.apache.kafka.common.errors.ClientConfigPolicyException;
import org.apache.kafka.common.errors.ConfigTooLargeException;
import org.apache.kafka.common.errors.UnknownConfigProfileException;
import org.apache.kafka.common.utils.Crc32C;

import java.nio.charset.StandardCharsets;
import java.util.Optional;
import java.util.SortedSet;
import java.util.stream.Collectors;

/**
 * An interface for intercepting and enforcing client configuration.
 *
 * <p>Common use cases include:
 * <ul>
 *   <li>Selecting which configuration keys to request from clients based on their profile</li>
 *   <li>Validating that client configurations match expected values or fall within acceptable ranges</li>
 *   <li>Storing client configuration snapshots for observability and troubleshooting</li>
 * </ul>
 *
 * <p>If <code>client.config.policy.class.name</code> is defined, Kafka will create an instance of the specified class
 * using the default constructor and will then pass the broker configs to its <code>configure()</code> method.
 * During broker shutdown, the <code>close()</code> method will be invoked so that resources can be released (if
 * necessary).
 */
@InterfaceStability.Evolving
public interface ClientConfigPolicy extends Reconfigurable, AutoCloseable {

    /**
     * Computes the CRC that serves to identify a configuration profile. The
     * value is generated by calculating a CRC32C of the configuration set.
     * <p>
     * This default implementation sorts the keys for deterministic ordering and computes
     * a CRC32C checksum. Implementations may override this method if a different CRC
     * calculation is needed.
     *
     * @param configKeys The set of configuration keys in the profile
     * @return CRC32C checksum of the configuration keys
     */
    default long configurationProfileCrc(SortedSet<String> configKeys) {
        // Sort keys for deterministic ordering
        String keysString = configKeys.stream()
            .collect(Collectors.joining(","));
        byte[] keysBytes = keysString.getBytes(StandardCharsets.UTF_8);
        return Crc32C.compute(keysBytes, 0, keysBytes.length);
    }

    /**
     * Select the configuration profile keys for a given client profile.
     * <p>
     * How much of the client profile must match a configuration profile is left up to the
     * implementation. It is not a requirement that all of the client profile (name, version, and
     * any optional metadata) match exactly. For example, if the configuration of the client doesn't
     * change between minor versions, there's no need to provide a distinct configuration profile
     * for each minor client profile difference.
     * <p>
     * If this method returns {@code Optional.empty()}, the client will not send a PushConfig request.
     *
     * @param clientProfile The client profile information from the request context
     * @return Optional containing the configuration profile keys and CRC, or empty if no profile matches
     * @throws UnknownConfigProfileException if the client profile did not match any configuration profiles
     *                                       and the policy implementation does not allow for that case
     */
    Optional<ClientConfigProfileKeys> profileKeys(ClientProfile clientProfile)
        throws UnknownConfigProfileException;

    /**
     * Receive the client configuration data for observability, enforcement, etc.
     * <p>
     * This method should avoid blocking. Implementations typically:
     * <ul>
     *   <li>Validate configuration values against expected ranges or patterns</li>
     *   <li>Store configuration snapshots in external storage for auditing</li>
     *   <li>Track configuration changes over time</li>
     * </ul>
     * <p>
     * <b>Note</b>: this method will <i>not</i> be invoked if the {@code Configs} array
     * of the PushConfig request was larger than {@code client.config.max.bytes}.
     *
     * @param pushConfigData The client profile and configuration data from the PushConfig request
     * @throws UnknownConfigProfileException if the configuration profile CRC is invalid or outdated
     * @throws ConfigTooLargeException if the configuration data exceeds size limits
     * @throws ClientConfigPolicyException if the configurations violate the policy
     */
    void process(ClientPushConfigData pushConfigData)
        throws UnknownConfigProfileException, ConfigTooLargeException, ClientConfigPolicyException;

    /**
     * Close this policy instance. Default implementation is a no-op.
     */
    @Override
    default void close() throws Exception {
        // Default no-op
    }
}
